mod algorithm;
mod binary_search;
mod interval;
mod judge;
mod lift;
mod mahler;
mod matrix;
mod proj;
mod rational_matrix;
mod specialize;
mod sturm;
mod univariate;

use algorithm::Solution;
pub use algorithm::find_solution;
pub use binary_search::calc_sample_points;
use binary_search::{refine_range, refine_root};
use judge::{is_possible_solution, is_possible_solution_interval};
use lift::lifting;
use mahler::{MahlerResult, evaluate_polynomial_by_mahler};
pub use proj::project_polynomial;
use proj::psc_0;
use rational_matrix::polynomial_matrix_determinant;
use specialize::{evaluate_polynomial_at_constants, specialize_polynomial};
use sturm::{Range, Root, find_unique_roots};
pub use univariate::{UnivariatePolynomial, polynomial_to_univariate};
use univariate::{uni_poly_derivative, uni_poly_div, uni_poly_remainder};
